### ISSUE TITLE
Font-Awesome files not found

### ISSUE THREAD

**Issue by benjaminwood** [cytopia/ansible-debian#32]
Looks like they changed the directory structure recently: https://github.com/FortAwesome/Font-Awesome/pull/14370/commits/e8f703a954bcae940c29417073d0fe1ad9da14ce

I assume they only moved these files elsewhere, but haven't looked into it yet.

**Comment by mo6020** [comment]
Yeh, they've moved the files. I'll submit a PR to fix this evening.

**Comment by cytopia** [comment]
This has been fixed by @mo6020 : https://github.com/cytopia/ansible-debian/pull/33

Thanks for the PR
