### ISSUE TITLE
Just ask if I can

### ISSUE THREAD

**Issue by Wabri** [cytopia/ansible-debian#36]
I use ansible too for my dotfiles and I have create a template repository that might interest you https://github.com/Wabri/Daje

Is it a problem if I see that some of your tasks are interesting and add them to my template repo?

**Comment by cytopia** [comment]
You can use this repository code according to MIT. See license of this project: https://github.com/cytopia/ansible-debian/blob/master/LICENSE.md

**Comment by Wabri** [comment]
Thank you 😁
